### ISSUE TITLE
Audio Control

### ISSUE THREAD

**Issue by hughjazzman** [R-Ramana/CG2271#5]
Audio needs to be configured: 

* The robot must continuously play a Song tune from the start of the challenge run till the end.
    * There should not be any break in the song even if the robot is not moving.
* When the robot completes the challenge run, the robot must play a unique tone to end the timing.

Code written needs to use a PWM pin to play the song. 

* Create functions to play the song and tone.

**Comment by hughjazzman** [comment]
Following from #3, this task can be done from PTA12 (Alt3) - TPM1_CH0.

**Comment by R-Ramana** [comment]
We have the following notes (purpose):
- Windows XP Shutdown Tone (BT Connection)
- Megalovania (When the robot is moving)
- Coffin Dance (Victory Tone)

**Comment by hughjazzman** [comment]
Playing duty cycle >40% seems to destroy the audio, so current setting is 33% duty cycle (1/3 of `MOD`).
